server:
  port: 8001
  error:
    include-stacktrace: on-param
spring:
  application:
    name: login-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/login?autoReconnect=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8005/eureka/

springdoc:
 api-docs:
   path: /login-docs
 swagger-ui:
   path: /swagger-ui.html
   
jwt:  
  secret: robotSpectorSecret
