server:
  port: 8001
  error:
    include-stacktrace: on-param
spring:
  application:
    name: login-microservice
  datasource:
    url: jdbc:mysql://login-service-mysql:3306/login?autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:  
  secret: robotSpectorSecret
