server:
  port: 8001
  error:
    include-stacktrace: on-param
spring:
  application:
    name: login-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: Karumari*08
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
