server:
  port: 8002
  
spring:
  application:
    name: equipment-service
  data:
    mongodb:
      database: equipment
      port: 27017
      host: localhost
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8005/eureka/