image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3.8.4-jdk-11-slim
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
