version: "3.9"
services:
  cgi-stackroute-mysql:
    image: "mysql:latest"
    environment:
      -  MYSQL_ROOT_PASSWORD=root123
    ports:
      -  3307:3306
    volumes:
      -  ./data/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  angular-app:
    image: "robospector-front-end"
    ports:
      -  4200:80
    depends_on:
      cgi-stackroute-mysql:
        condition: service_healthy
    build:
      context: "./robotspector_frontend"
      dockerfile: "Dockerfile"