version: "3.9"

networks:
  main-network:
    external:
      name: $NETWORK_NAME

services:
  login-service-mysql:
    image: "mysql:latest"
    container_name: login-service-mysql
    hostname: login-service-mysql
    restart: unless-stopped
    ports:
      -  $LOGIN_MY_SQL_HOST_PORT:3306
    environment:
      -  MYSQL_ROOT_PASSWORD=$LOGIN_MY_SQL_ROOT_PASSWORD
    volumes:
      -  $LOGIN_MY_SQL_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    networks:
      -  main-network

  angular-app:
    image: "robospector-front-end"
    ports:
      -  4200:80
    depends_on:
      -  login-service-mysql
    build:
      context: "./robotspector_frontend"
      dockerfile: "Dockerfile"
    networks:
      -  main-network

  login-service:
    build:
      context: "./LoginMicroService"
      dockerfile: "Dockerfile"
    image: $LOGIN_APP_NAME
    container_name: $LOGIN_APP_NAME
    restart: on-failure
    depends_on:
      - mongo
    ports:
      -  $LOGIN_SERVER_HOST_PORT:8001
    environment:
      -  SERVER_PORT=8001
      -  SPRING_PROFILES_ACTIVE=prod
      -  SPRING_APPLICATION_NAME=$LOGIN_APP_NAME
      -  SPRING_DATASOURCE_URL=jdbc:mysql://login-service-mysql:3306/login?autoReconnect=true
      -  SPRING_DATASOURCE_USERNAME=$LOGIN_MY_SQL_ROOT_USERNAME
      -  SPRING_DATASOURCE_PASSWORD=$LOGIN_MY_SQL_ROOT_PASSWORD
    networks:
      -  main-network
