server:
  port: 8004
spring:
  application:
    name: inspection-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inspections
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8005/eureka/